name: 'GitHub Action for Perl Critic'
description: 'Run Perl Critic on your codebase.'
author: Difegue
branding:
  color: blue
  icon: eye
inputs:
  args:
    description: 'args'
  repo-token:
    description: 'repo-token'
  github_token:
    description: 'GITHUB_TOKEN.'
    default: '${{ github.token }}'
runs:
  using: composite
  steps:
    - run: |
        export INPUT_GITHUB_TOKEN=${{ inputs.github_token }};
        FILEPATH="${{ github.action_path }}/entrypoint.sh"
        if [ -f "$FILEPATH" ]; then
          chmod +x $FILEPATH
          $FILEPATH
        else
          # Exit as not found ( in bash exit code )
          exit 127
        fi
      shell: bash
